name: Arroyo Action Demo
on: [push]
jobs:
  First-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‘ Job inicializado"
      - run: echo "ğŸ¤¦â€â™€ï¸ Primera ejececucion ${{ runner.os }}"
      - run: echo "âœ” ya casi terminaj... pero estamos con el Branch ${{ github.ref }}"
      - name: Get Repository
        uses: actions/checkout@v3
      - run: echo "Repositorio ${{ github.repository }}"
      - run: echo "Hemos terminado"
